In [1]:
import numpy as np
import sys

In [2]:
#Print all numbers from 0 to 15
a = np.arange(15)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [3]:
#Print all numbers from 0 to 15 with steps of 3
a = np.arange(0, 15, 3)
print(a)

[ 0  3  6  9 12]


In [4]:
b = a.reshape(1, 5)
print(b)

[[ 0  3  6  9 12]]


In [5]:
# Shape
print(b.shape)

(1, 5)


In [6]:
# Number of dimension
print(b.ndim)

2


In [7]:
# Print datatype
print(b.dtype.name)

int32


In [8]:
# Size of a
print(a.size)
print(b.size)

5
5


In [9]:
print(type(a))
print(type(b))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [10]:
# Implicity hardcoding
c = np.array([4,7,13])
print(c)

[ 4  7 13]


In [11]:
# Add complex functions
d = np.array([[12,36,8],[47,96,37]], dtype = complex)
print(d)

[[12.+0.j 36.+0.j  8.+0.j]
 [47.+0.j 96.+0.j 37.+0.j]]


In [12]:
print(d.max(axis = 1))

[36.+0.j 96.+0.j]


In [13]:
print(d.sum())

(236+0j)


In [14]:
# Print ones
e = np.ones(4)
print(e)

[1. 1. 1. 1.]


In [15]:
f = np.ones((4,5))
print(f)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [16]:
print(f)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [17]:
zeros = np.zeros((4,2,3))
print(zeros)

[[[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]]


In [18]:
# When number of elements is needed and not necessarily steps
g = np.linspace(0, 3, 9)
print(g)

[0.    0.375 0.75  1.125 1.5   1.875 2.25  2.625 3.   ]


In [19]:
A = np.array([45, 60, 87, 43])
B = np.arange(4)
print(B)

[0 1 2 3]


In [20]:
print('Sum of A and B  {} '.format(A + B))

Sum of A and B  [45 61 89 46] 


In [21]:
print('Difference of A and B  {} '.format(A - B))

Difference of A and B  [45 59 85 40] 


In [22]:
print('Square of B {} '.format(B**2))

Square of B [0 1 4 9] 


In [23]:
print('Cos of  B  {} '.format( np.cos(B)))

Cos of  B  [ 1.          0.54030231 -0.41614684 -0.9899925 ] 


In [24]:
print('Matrix product of A and B  {} '.format(A @ B))

Matrix product of A and B  363 


In [25]:
print('Matrix product of A and B  {} '.format(A.dot(B)))

Matrix product of A and B  363 


In [26]:
 C = [4,87,3,25,7,89,56,36,7]

In [27]:
C

[4, 87, 3, 25, 7, 89, 56, 36, 7]

In [28]:
# Slicing from start
print(C[:4])

[4, 87, 3, 25]


In [29]:
#Slicing from 2 till a givem value
print(C[2:7])

[3, 25, 7, 89, 56]


In [30]:
# Slice from 5 to end
print(C[5:])

[89, 56, 36, 7]


In [31]:
# Takes the lowest possible in the range
D = np.linspace(0, 7, 21)
D

array([0.  , 0.35, 0.7 , 1.05, 1.4 , 1.75, 2.1 , 2.45, 2.8 , 3.15, 3.5 ,
       3.85, 4.2 , 4.55, 4.9 , 5.25, 5.6 , 5.95, 6.3 , 6.65, 7.  ])

In [32]:
print(np.floor(D))

[0. 0. 0. 1. 1. 1. 2. 2. 2. 3. 3. 3. 4. 4. 4. 5. 5. 5. 6. 6. 7.]


In [33]:
# Reshape to 7 by 3
shaped = D.reshape((7,3))
print(shaped)

[[0.   0.35 0.7 ]
 [1.05 1.4  1.75]
 [2.1  2.45 2.8 ]
 [3.15 3.5  3.85]
 [4.2  4.55 4.9 ]
 [5.25 5.6  5.95]
 [6.3  6.65 7.  ]]


In [34]:
# Flatten the data
flattened = shaped.ravel()
print(flattened)

[0.   0.35 0.7  1.05 1.4  1.75 2.1  2.45 2.8  3.15 3.5  3.85 4.2  4.55
 4.9  5.25 5.6  5.95 6.3  6.65 7.  ]


In [35]:
transpoused = shaped.T
print(transpoused)

[[0.   1.05 2.1  3.15 4.2  5.25 6.3 ]
 [0.35 1.4  2.45 3.5  4.55 5.6  6.65]
 [0.7  1.75 2.8  3.85 4.9  5.95 7.  ]]


In [36]:
# Vertical stacking
print(np.vstack((A,B)))

[[45 60 87 43]
 [ 0  1  2  3]]


In [37]:
# horizontal stacking
print(np.hstack((A,B)))

[45 60 87 43  0  1  2  3]
